import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {compile,fn,raw,nodes,h,hooks,jsx,Fragment,repo,read,evaluate} from '../../LWB317-UI-AUTOMATION-AFK-CLOSEOUT-001/harness.mjs';
import * as contracts from '../../../../../src/LWBridge.UI-0.3.17/src/previewRemainingPagesContracts.js';
export {contracts,hooks,compile,h,jsx,repo,read,fn,raw,nodes};
export const root=path.dirname(fileURLToPath(import.meta.url));
const require=createRequire(path.join(repo,'src/LWBridge.UI-0.3.17/package.json'));
export const React=require('react');
const {renderToStaticMarkup}=require('react-dom/server');
const {transformSync}=require('esbuild');
export const assets='evidence/lwbridge-0.3.17/ui/frontend-package/web/assets/';
export const index=read(assets+'index-BVfnK1wp.js');
export const hotkeySource=read(assets+'HotkeyPanel-XA8idRHB.js');
export const settingsSource=read(assets+'SettingsPanel-DqxIWv_E.js');
export const citySource=read(assets+'CityLayoutPanel-DoNWkywK.js');
export const clock=1770026400000;
export class FixedDate extends Date {constructor(...args){super(...(args.length?args:[clock]));}static now(){return clock;}}
const files={en:'en-BisSXcTB.js',ja:'ja-UrbzJu-m.js',ru:'ru-YncvPDv4.js',ko:'ko-SaFvwwmo.js',vi:'vi-BAUQ1cwP.js',id:'id-D9oeC8zM.js',pt:'pt-BaH2E9ai.js','zh-CN':'zh-CN-ByrbNejR.js','zh-TW':'zh-TW-B9GVGLk3.js'};
const bases={};for(const name of ['jr','Mr','Nr','Pr','Fr']){const d=nodes(index).find(n=>n.type==='VariableDeclarator'&&n.id?.name===name&&n.start>249000);bases[name]=evaluate(raw(index,d.init),bases);}
export const originalCatalogs=Object.fromEntries(Object.entries(files).map(([lang,file])=>{const source=read(assets+file);const object=nodes(source).find(n=>n.type==='VariableDeclarator'&&n.id?.name==='t');return[lang,evaluate(raw(source,object.init),{e:bases.Fr})];}));
export const currentCatalogs={};
for(const lang of Object.keys(files))currentCatalogs[lang]=(await import(pathToFileURL(path.join(repo,`src/LWBridge.UI-0.3.17/src/locales/${lang}.js`)))).default;
export const translate=catalog=>(key,vars={})=>String(catalog[key]??key).replace(/\{(\w+)\}/g,(m,k)=>String(vars[k]??m));
export const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
export const fakeWindow={setInterval:()=>1,clearInterval(){},setTimeout:()=>1,clearTimeout(){},addEventListener(){},removeEventListener(){},getComputedStyle:()=>({paddingLeft:'0',paddingTop:'0'}),confirm:()=>false};
export function moduleFunctions(file,names,env){let source=read('src/LWBridge.UI-0.3.17/src/'+file);source=source.replace(/^import .*?;\r?\n/gm,'').replace(/export /g,'');const code=transformSync(source,{loader:'jsx',jsxFactory:'h',jsxFragment:'Fragment'}).code;return new Function(...Object.keys(env),code+'\nreturn {'+names.join(',')+'};')(...Object.values(env));}
export function shared(lang,original=false){const t=translate((original?originalCatalogs:currentCatalogs)[lang]);if(original){const Switch=compile(index,'zn',{M:jsx});const ToggleRow=compile(index,'Bn',{De:()=>({t}),M:jsx,zn:Switch});return{Switch,ToggleRow};}return moduleFunctions('sharedPageUI.jsx',['Switch','ToggleRow','PanelTitle'],{h,Fragment,useI18n:()=>({t})});}
export function toReact(node,key='root'){if(node==null||typeof node==='boolean')return null;if(Array.isArray(node))return node.map((n,i)=>toReact(n,key+'.'+i));if(typeof node!=='object')return node;if(typeof node.type==='function')return toReact(node.type(node.props??{}),key);const {children,...props}=node.props??{};props.key=key;if(node.type==='Fragment')return React.createElement(React.Fragment,{key},toReact(children,key+'.c'));return React.createElement(node.type,props,toReact(children,key+'.c'));}
export const markup=tree=>renderToStaticMarkup(toReact(tree));
export function currentHotkey(state,lang='en',category='hotkeys'){const hook=hooks();const t=translate(currentCatalogs[lang]);const module=moduleFunctions('HotkeyPages.jsx',['RecoveredHotkeyPanel'],{h,Fragment,...hook,...contracts,...shared(lang),useI18n:()=>({t}),window:fakeWindow,Date:FixedDate});const render=()=>{hook.begin();return module.RecoveredHotkeyPanel({previewState:state,category,online:false});};return{hook,render,state};}
export function originalHotkeyFromCurrent(current,lang='en',category='hotkeys'){const t=translate(originalCatalogs[lang]);const v=current.hook.values;const seed=[v[0],v[1],v[4],v[5],v[6],v[7],v[9],v[2]];
 const hook=hooks(seed);const originalShared=shared(lang,true);const p=nodes(hotkeySource).find(n=>n.type==='VariableDeclarator'&&n.id?.name==='p');const m=nodes(hotkeySource).find(n=>n.type==='VariableDeclarator'&&n.id?.name==='m');const Panel=compile(hotkeySource,'_',{d:hook,f:jsx,p:evaluate(raw(hotkeySource,p.init)),m:evaluate(raw(hotkeySource,m.init)),i:()=>({t}),l:originalShared.Switch,s:originalShared.ToggleRow,r:async()=>v[0],c:async x=>x,a:async()=>({cellId:17}),o:async()=>{},u:async()=>{},h:compile(hotkeySource,'h'),g:compile(hotkeySource,'g'),Date:FixedDate,window:fakeWindow});hook.begin();return Panel({category,online:category==='miniGames'?current.state!=='mini-games-offline':current.state==='hotkeys-connected'||current.state==='hotkeys-saving',onLog(){},sheepStatus:v[8]});}
export function currentSettings(state,lang='en'){const hook=hooks();const t=translate(currentCatalogs[lang]);const module=moduleFunctions('SettingsPage.jsx',['SettingsPage'],{h,Fragment,...hook,...contracts,...shared(lang),useI18n:()=>({t,language:lang}),window:fakeWindow,Date:FixedDate});const render=()=>{hook.begin();return module.SettingsPage({previewState:state});};return{hook,render,state};}
export function originalSettingsFromCurrent(current,lang='en'){const v=current.hook.values;const t=translate(originalCatalogs[lang]);const sh=shared(lang,true);const feedback=v[5];const feedbackHook=hooks([feedback.phase,feedback.result,feedback.progress,{current:''}]);const feedbackPanel=compile(settingsSource,'p',{u:feedbackHook,d:jsx,o:()=>({t}),e:()=>()=>{},a:async()=>({}),f:compile(settingsSource,'f'),crypto:{randomUUID:()=>''}});const updateHook=hooks([v[6],v[7]]);const updater=compile(index,'Rn',{b:updateHook,M:jsx,De:()=>({t,language:lang}),Ln:v[6],dt:()=>()=>{},ct:async()=>v[6],lt:async()=>v[6],ut:async()=>v[6],window:fakeWindow,Date:FixedDate});
 const hook=hooks([v[0],v[1],v[2]]);const panel=compile(settingsSource,'m',{u:hook,d:jsx,o:()=>({t}),r:async()=>v[0],l:async x=>x,c:sh.ToggleRow,p:()=>{feedbackHook.begin();return feedbackPanel();},s:()=>{updateHook.begin();return updater({compact:false});}});hook.begin();return panel({showProfileFocus:['settings-complete','settings-multiprofile'].includes(current.state),focusGameOnProfileSelect:v[4],onFocusGameOnProfileSelectChange(){}});}
export function imageComponent(original=false){const hook=hooks();if(original){const source=read(assets+'GameAssetImage-Diy9VTIr.js');const Component=compile(source,'x',{i:hook,a:jsx,b:compile(source,'b'),l:new Map(),y:()=>()=>{},window:fakeWindow});return props=>{hook.values.length=0;hook.begin();return Component(props);};}const module=moduleFunctions('GameAssetImage.jsx',['GameAssetImage'],{h,Fragment,...hook,createContext:()=>({}),useContext:()=>null});return props=>{hook.values.length=0;hook.begin();return module.GameAssetImage(props);};}
export function currentCity(state,lang='en'){const hook=hooks();const t=translate(currentCatalogs[lang]);const module=moduleFunctions('CityLayoutPage.jsx',['CityLayoutPage'],{h,Fragment,...hook,...contracts,useI18n:()=>({t}),window:fakeWindow,document:{activeElement:null},Date:FixedDate,GameAssetImage:imageComponent()});const render=()=>{hook.begin();return module.CityLayoutPage({previewState:state,online:false});};return{hook,render,state};}
export function originalCityFromCurrent(current,lang='en'){const state=current.state;const fixture=['city-layout-loading','city-layout-error',''].includes(state)?null:contracts.previewCityLayoutFixture(state);const v=current.hook.values;const t=translate(originalCatalogs[lang]);const seed=[fixture,v[0],v[1],v[5],undefined,v[2],v[3],{},v[8],fixture?.layoutRevision??'',v[9],state==='city-layout-loading',v[10],v[7],state==='city-layout-applying'?{state:'running',totalMoves:4,completedMoves:2,jobId:'preview-city-layout'}:null,v[12], '',[],0,null];const hook=hooks(seed);const env={window:fakeWindow,document:{activeElement:null},Date:FixedDate};for(const name of ['te','ne','m','re','ie','ae','oe','le','g'])env[name]=compile(citySource,name,env);Object.assign(env,{p:{...hook,useCallback:fn=>fn},h:jsx,s:()=>({t,language:lang}),se:{past:[],present:[],future:[]},ce:24,ee:imageComponent(true)});const Panel=compile(citySource,'ue',env);hook.begin();return Panel({profileId:'inert',online:state!=='',onLog(){}});}
