import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {root,repo,read,assets,fn,raw,nodes,hash,markup,currentCity,originalCityFromCurrent,currentHotkey,originalHotkeyFromCurrent,currentSettings,originalSettingsFromCurrent,citySource,hotkeySource,settingsSource,index,originalCatalogs,currentCatalogs} from './page-harness.mjs';
const campaign=path.dirname(root);
if(process.argv.includes('--verify'))fs.writeFileSync=(file,data)=>assert.equal(fs.readFileSync(file,'utf8'),String(data),'Fresh original/current render inventory drift: '+file);
const output=process.argv.includes('--baseline')?'baseline':'current';
const specs=[
 {unit:'e',page:'city-layout',file:'CityLayoutPage.jsx',source:citySource,original:'CityLayoutPanel-DoNWkywK.js',functions:['ue','te','ne','m','re','ie','ae','oe','le','g'],states:['','city-layout-loading','city-layout-error','city-layout-populated','city-layout-populated-moved','city-layout-populated-conflict','city-layout-stale','city-layout-outside-city','city-layout-server-valid','city-layout-applying'],current:currentCity,originalRender:originalCityFromCurrent,representative:'city-layout-populated-moved'},
 {unit:'f',page:'hotkeys',file:'HotkeyPages.jsx',source:hotkeySource,original:'HotkeyPanel-XA8idRHB.js',functions:['_'],states:['hotkeys-disconnected','hotkeys-connected','hotkeys-loading','hotkeys-load-error','hotkeys-saving','hotkeys-save-error'],current:(s,l)=>currentHotkey(s,l,'hotkeys'),originalRender:(c,l)=>originalHotkeyFromCurrent(c,l,'hotkeys'),representative:'hotkeys-disconnected'},
 {unit:'g',page:'mini-games',file:'HotkeyPages.jsx',source:hotkeySource,original:'HotkeyPanel-XA8idRHB.js',functions:['_','h','g'],states:['mini-games-active','mini-games-offline','mini-games-config-loading','mini-games-load-error','mini-games-config-saving','mini-games-save-error','mini-games-land-success','mini-games-land-error','mini-games-land-opening','mini-games-sheep-pending','mini-games-start-failed','mini-games-solving','mini-games-executing','mini-games-completed','mini-games-complete','mini-games-all-complete','mini-games-activity-ended','mini-games-ui-open','mini-games-conflict','mini-games-solve-failed','mini-games-unsupported','mini-games-refreshing','mini-games-starting','mini-games-opening','mini-games-initial-delay','mini-games-state-error'],current:(s,l)=>currentHotkey(s,l,'miniGames'),originalRender:(c,l)=>originalHotkeyFromCurrent(c,l,'miniGames'),representative:'mini-games-active'},
 {unit:'h',page:'settings',file:'SettingsPage.jsx',source:settingsSource,original:'SettingsPanel-DqxIWv_E.js',functions:['m','p','f'],states:['settings-complete','settings-multiprofile','settings-visual-loading','settings-visual-error','settings-visual-saving','settings-visual-save-error','settings-feedback-preparing','settings-feedback-exporting','settings-feedback-finalizing','settings-feedback-success','settings-feedback-error','settings-feedback-canceled','settings-update-idle','settings-update-checking','settings-update-available','settings-update-downloading','settings-update-opening','settings-update-error','settings-update-check-error','settings-update-download-error','settings-update-cooldown'],current:currentSettings,originalRender:originalSettingsFromCurrent,representative:'settings-complete'},
];
const exe=path.resolve(repo,'../LW/lwbridge-0.3.17.exe');assert.equal(hash(fs.readFileSync(exe)),'4e9c3113dedfd7e1a752404c6936aab304e67d7ffdb0952a5003c2ec948d6783');
const originalCSS=read(assets+'index-rIL9Fpht.css');const currentCSS=read('src/LWBridge.UI-0.3.17/src/reference.css')+'\n'+read('src/LWBridge.UI-0.3.17/src/styles.css');
const modes=[['en','light',1280,900],['ja','dark',1280,900],['en','dark',375,1000],['ja','light',375,1000],['ru','dark',375,1000]];
for(const spec of specs){const dir=path.join(campaign,'unit-'+spec.unit,output);fs.mkdirSync(path.join(dir,'raw'),{recursive:true});const file=path.join(repo,'src/LWBridge.UI-0.3.17/src',spec.file);if(output==='baseline')fs.copyFileSync(file,path.join(dir,spec.file));
 const inventory={page:spec.page,states:spec.states,proof:'EXACT_CONTRACT; synthetic hook states supplied to actual source functions, effects intentionally inert',functions:spec.functions.map(name=>{const n=fn(spec.source,name);return{name,path:assets+spec.original,utf8Offset:Buffer.byteLength(spec.source.slice(0,n.start)),bytes:Buffer.byteLength(raw(spec.source,n)),sha256:hash(raw(spec.source,n))};}),native:'No commands, OS hotkeys, providers, diagnostics, updater or gameplay invoked',clock:1770026400000,timezone:'Asia/Singapore',currentSource:{path:path.relative(repo,file).replaceAll('\\','/'),sha256:hash(fs.readFileSync(file))},originalCSS:{path:assets+'index-rIL9Fpht.css',sha256:hash(originalCSS)},dependencyPaths:['unit-e/page-harness.mjs','unit-e/recover-pages.mjs'],substitutions:['State/ref seeds disclosed in page-harness.mjs','useMemo/useCallback executed synchronously; effects not executed in static source proof','Actual recovered/current GameAssetImage both rendered unresolved-source placeholder, no invented image'],statesRendered:[]};
 for(const lang of ['en','ja','ru'])for(const state of spec.states){const current=spec.current(state,lang);const currentHTML=markup(current.render());const originalHTML=markup(spec.originalRender(current,lang));const id=(state||'offline')+'-'+lang;fs.writeFileSync(path.join(dir,'raw',id+'-current.html'),currentHTML);fs.writeFileSync(path.join(dir,'raw',id+'-original.html'),originalHTML);inventory.statesRendered.push({state,lang,id,rawEqual:currentHTML===originalHTML,currentSha256:hash(currentHTML),originalSha256:hash(originalHTML)});}
 const pairs=[];for(const[lang,theme,width,height]of modes){const state=spec.representative;const id=`${spec.page}-${lang}-${theme}-${width}`;for(const side of ['original','current']){const body=fs.readFileSync(path.join(dir,'raw',`${state}-${lang}-${side}.html`),'utf8');fs.writeFileSync(path.join(dir,id+'-'+side+'.html'),`<!doctype html><html lang="${lang}" data-theme="${theme}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${side==='original'?originalCSS:currentCSS}</style></head><body><section class="main-view">${body}</section></body></html>`);}pairs.push({id,state,lang,theme,width,height});}inventory.pairs=pairs;
 const keys=[...new Set(nodes(spec.source).filter(n=>n.type==='StringLiteral'||n.type==='TemplateLiteral'&&n.expressions.length===0).map(n=>n.value??n.quasis[0].value.cooked).filter(s=>/^(hotkeys|miniGames|settings|feedback|update|cityLayout|common|status)\./.test(s)))];const locale={keys,values:Object.fromEntries(Object.keys(originalCatalogs).map(lang=>[lang,keys.map(key=>({key,original:originalCatalogs[lang][key]??null,current:currentCatalogs[lang][key]??null,equal:originalCatalogs[lang][key]===currentCatalogs[lang][key]}))]))};assert.ok(Object.values(locale.values).flat().every(e=>e.equal),'Original/current locales mismatch');fs.writeFileSync(path.join(dir,'locale-inventory.json'),JSON.stringify(locale,null,2)+'\n');fs.writeFileSync(path.join(dir,'inventory.json'),JSON.stringify(inventory,null,2)+'\n');console.log(spec.page,inventory.statesRendered.length,'actual paired render states');}
